// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Admin struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

type User struct {
	ID        int32        `json:"id"`
	UserID    string       `json:"user_id"`
	Username  string       `json:"username"`
	CreatedAt sql.NullTime `json:"created_at"`
}
